### ISSUE TITLE
Biased amplifier example error

### ISSUE THREAD

**Issue by jClugstor** [CedarEDA/PublicIssues#2]
For the biased amplifier example, in `amplifier_sensitivity.jl` the line `ssols = sensitivities!(sp)` gives the error `MethodError: frule(::Tuple{ChainRulesCore.ZeroTangent, Float64}, ::typeof(one), ::Float64) is ambiguous.` 

I was getting this error from a fresh REPL, just by running the file `amplifier_sensitivity.jl` line by line until  `ssols = sensitivities!(sp)`.

**Comment by Keno** [comment]
Assigned @oxinabox . Also should look into why this didn't get caught on pre-deployment CI.

**Comment by oxinabox** [comment]
I know what caused this, but I don't know why CI didn't catch it.
It is an issue that has been fixed already in ChainRules.jl and ChainRulesCore.jl.
See https://github.com/JuliaDiff/ChainRules.jl/issues/769
If we pull the latest versions of those it should be all fixed.

I will look into why CI didn't catch it.

**Comment by Keno** [comment]
This issue has been fixed internally and will be deployed with the next version. I'll leave this open until the fix is deployed.

We also understand what went wrong in the deployment process and will work towards additional checks on the deployed version, but that'll take a bit longer.

**Comment by staticfloat** [comment]
This has now been fixed and is live on juliahub.com.  Thank you for the bug report!
