### ISSUE TITLE
Add support for SPICE behavioral sources

### ISSUE THREAD

**Issue by ggkountouras** [CedarEDA/PublicIssues#5]
Behavioral sources (B sources in SPICE terminology) are useful for defining custom components. For instance, a transistor can be defined as:

```* npn Bipolar Junction Transistor (Ebers-Moll)
.subckt npnBJTEbersMoll C B E
.param isc=1e-14 ise=1e-14 eta_c=1 eta_e=1 alpha_f=0.9901 alpha_r=0.5 vT=25e-3
B1 B C I={alpha_f*ise*(exp(V(B,E)/(eta_e*vT)) - 1) - isc*(exp(V(B,C)/(eta_c*vT)) - 1)}
B2 B E I={ise*(exp(V(B,E)/(eta_e*vT)) - 1) - alpha_r*isc*(exp(V(B,C)/(eta_c*vT)) - 1)}
.ends
```
Support for these arbitrary voltage and current sources, as well as [their SPICE syntax](https://help.juliahub.com/cedareda/dev/user_guide/syntax_support/spice_syntax/) should be added.

**Comment by pepijndevos** [comment]
We do have some support for B sources. I can try your bjt circuit tomorrow but if you have a particular test circuit or error message that could be helpful. I've recently been expanding our support for E and G sources as well.

**Comment by pepijndevos** [comment]
Actually only a one-line fix was required to make `V(B,C)` case insensitive but otherwise your circuit parses and simulates.

```
.subckt npnBJTEbersMoll C B E
.param isc=1e-14 ise=1e-14 eta_c=1 eta_e=1 alpha_f=0.9901 alpha_r=0.5 vT=25e-3
B1 B C I={alpha_f*ise*(exp(V(B,E)/(eta_e*vT)) - 1) - isc*(exp(V(B,C)/(eta_c*vT)) - 1)}
B2 B E I={ise*(exp(V(B,E)/(eta_e*vT)) - 1) - alpha_r*isc*(exp(V(B,C)/(eta_c*vT)) - 1)}
.ends

v1 vcc 0 5
v2 in 0 SIN(2, 0.5, 10)
r1 in base 1k
r2 vcc coll 1k
x1 coll base 0 npnBJTEbersMoll
```

I can't say the results match though, so a bit more debugging is in order.

![image](https://github.com/CedarEDA/PublicIssues/assets/168609/4c86a03f-4ff6-4bdc-bd21-e73c9a1d9dea)
![npn](https://github.com/CedarEDA/PublicIssues/assets/168609/1341668e-8fe1-4a33-99b4-bdf656417645)

**Comment by pepijndevos** [comment]
I get a good match on some more basic behavioural sources (effectively just resistors)
![image](https://github.com/CedarEDA/PublicIssues/assets/168609/8bc30dfb-a173-4888-8ba4-d24c26a6bd48)

**Comment by pepijndevos** [comment]
A diode like this also pretty much works
```
B1 P 0 I={ise*(exp(V(P,0)/(eta_e*vT)) - 1)}
```
![image](https://github.com/CedarEDA/PublicIssues/assets/168609/6a879963-e4be-4a72-aeee-96cb2f713e57)

So far nothing obviously wrong, and yet...

**Comment by pepijndevos** [comment]
I'm not sure what's wrong with the NPN circuit, but both the ngspice result and the cedar result don't make sense for an NPN, so there might be a model error? The ngspice result is below zero while the cedar result is above the supply.

At least the issues of "do we support B sources" seems resolved. With a side note that we currently do not support POLY and TABLE syntax.
